### ISSUE TITLE
We need to plan out how we want the database to look

### ISSUE THREAD

**Issue by hjarrell** [ufosc/GatorQuestions#14]
We should plan out the different tables we need now and then code it so we reach a good consensus.

**Comment by alexandershuping** [comment]
I would propose using [this schema](https://app.sqldbm.com/MySQL/Share/3Qju0zHO_lamyGyv69r4ikGFrngIE8md_DYjF4jNYw0) for handling user permissions (as part of a larger database structure, of course):

- All users are stored in the same 'user' table, regardless of role (students, professors, etc).
- Users are associated with both 'global' and 'course' roles.
- Roles are associated with permissions, which determine exactly what a user is allowed to do. 'global' permissions are associated with 'global' roles, while 'course' permissions are associated with 'course' roles.
- 'global' roles are set up by the installation site. 'global' permissions control things like the ability to create/delete courses.
- 'course' roles, on the other hand, are controlled by the master-admin of a course (usually, this will be the professor). 'course' permissions determine a user's ability to view/edit/create/delete questions, take attendance, etc.
- Additionally, 'course' roles and permissions are course-specific - a student TA user might have edit/create-question/view-grades permissions for the course they TA, but not for their other courses.

Individual permissions would likely be hard-coded in the program; however, roles would allow professors and site-managers to control permissions in a configurable and flexible way.
